# syntax=docker/dockerfile:1.17
# check=error=true
# The first line fixes the Dockerfile frontend used by BuildKit. For details
# see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim-amd64

ARG GROUP_ID
ARG USER_ID

# Create non-root user to run commands in (see https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)
RUN \
  existing_user_name="$(getent passwd ${USER_ID} 2>/dev/null | cut --delimiter=: --fields=1)" && \
  existing_group_name="$(getent group ${GROUP_ID} 2>/dev/null | cut --delimiter=: --fields=1)" && \
  if test -n "${existing_user_name}"; then deluser --system "${existing_user_name}"; fi && \
  if test -n "${existing_group_name}"; then delgroup --system "${existing_group_name}"; fi && \
  addgroup --system --gid ${GROUP_ID} us && \
  adduser --system --uid ${USER_ID} --ingroup us me

# Install up-to-date GnuPG from the official GnuPG repository
# For available versions see https://repos.gnupg.org/deb/gnupg/
ENV GNUPG_VERSION=2.4.8-2
RUN set -eux && \
  version_codename=$(env --ignore-environment bash -c '. /etc/os-release; echo $VERSION_CODENAME') && \
  apt-get update && \
  apt-get install \
    --assume-yes \
    --no-install-recommends \
    curl \
    gnupg2 && \
  curl \
    --silent \
    --show-error \
    https://repos.gnupg.org/deb/gnupg/${version_codename}/gnupg-signing-key.gpg \
    | gpg --dearmor \
    > /usr/share/keyrings/gnupg-keyring.gpg && \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gnupg-keyring.gpg] https://repos.gnupg.org/deb/gnupg/${version_codename}/ ${version_codename} main" \
    > /etc/apt/sources.list.d/gnupg.list && \
  apt-get update && \
  apt-get install \
    --assume-yes \
    --no-install-recommends \
    dirmngr \
    gnupg2=${GNUPG_VERSION} && \
  rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*

ENV HOME=/home/me
RUN \
  mkdir --parents ${HOME} && \
  chown \
    me:us \
    ${HOME}

USER me
WORKDIR /app

RUN \
  mkdir --parents ${HOME}/.dotnet

ENV PATH=$PATH:/home/me/.dotnet/tools
RUN \
  dotnet tool install --global \
    dotnet-script
