using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Database.Migrations
{
    /// <inheritdoc />
    public partial class AssertExistenceOfAccessPolicyAndRootResourceInPostgreSql : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() CASCADE;");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() RETURNS trigger as $LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$\r\nBEGIN\r\n  IF (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\"\n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\"\n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\"\n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\"\n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\"\n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\"\n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a data access policy without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data BEFORE DELETE\r\nON \"database\".\"data_access_policy\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"CalorimetricDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"calorimetric_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"CalorimetricDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"CalorimetricDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"calorimetric_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_geometric_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_geometric_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"GeometricDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"GeometricDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_geometric_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_geometric_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"geometric_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_geometric_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_geometric_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_geometric_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"GeometricDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_geometric_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_geometric_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"geometric_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_geometric_data_assert_existence_of_root_resource\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data\"() RETURNS trigger as $LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data$\r\nBEGIN\r\n  IF OLD.\"ParentId\" IS NULL AND (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\" \n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\" \n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\" \n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\" \n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\" \n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\" \n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a root resource without also deleting the corresponding data in the same transaction.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data BEFORE DELETE\r\nON \"database\".\"get_https_resource\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"HygrothermalDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"HygrothermalDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"hygrothermal_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"HygrothermalDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"hygrothermal_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"LifeCycleDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"LifeCycleDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"lifeCycle_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"LifeCycleDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"lifeCycle_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_optical_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_optical_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"OpticalDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"OpticalDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_optical_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_optical_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"optical_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_optical_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_optical_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_optical_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"OpticalDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_optical_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_optical_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"optical_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_optical_data_assert_existence_of_root_resource\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary\"() RETURNS trigger as $LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary$\r\nBEGIN\r\n  INSERT INTO \"data_access_policy\"\n(\"PhotovoltaicDataId\", \"Combinator\")\nVALUES (NEW.\"Id\", 'all')\nON CONFLICT (\"PhotovoltaicDataId\") DO NOTHING;\nRETURN NEW;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary AFTER INSERT\r\nON \"database\".\"photovoltaic_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary\"();");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource\"() RETURNS trigger as $LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource$\r\nBEGIN\r\n  IF NOT EXISTS (\n    SELECT 1 FROM database.\"get_https_resource\"\n    WHERE \"ParentId\" IS NULL\n    AND \"PhotovoltaicDataId\" = NEW.Id\n)\nTHEN\n    RAISE EXCEPTION 'You cannot insert data without also inserting the corresponding root resource in the same transaction.';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource$ LANGUAGE plpgsql;\r\nCREATE CONSTRAINT TRIGGER LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource AFTER INSERT\r\nON \"database\".\"photovoltaic_data\"\r\nDEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource\"();");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_calorimetric_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_calorimetric_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_geometric_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_geometric_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_get_https_resource_root_can_only_be_deleted_alongside_its_data\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_hygrothermal_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_hygrothermal_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_life_cycle_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_life_cycle_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_optical_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_optical_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_create_photovoltaic_data_access_policy_if_necessary\"() CASCADE;");

            migrationBuilder.Sql("DROP FUNCTION \"database\".\"LC_TRIGGER_photovoltaic_data_assert_existence_of_root_resource\"() CASCADE;");

            migrationBuilder.Sql("CREATE FUNCTION \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"() RETURNS trigger as $LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$\r\nBEGIN\r\n  IF (\n    (OLD.\"CalorimetricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"calorimetric_data\" \n    WHERE \"Id\" = OLD.\"CalorimetricDataId\"\n)) OR (OLD.\"GeometricDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"geometric_data\" \n    WHERE \"Id\" = OLD.\"GeometricDataId\"\n)) OR (OLD.\"HygrothermalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"hygrothermal_data\" \n    WHERE \"Id\" = OLD.\"HygrothermalDataId\"\n)) OR (OLD.\"LifeCycleDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"lifeCycle_data\" \n    WHERE \"Id\" = OLD.\"LifeCycleDataId\"\n)) OR (OLD.\"OpticalDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"optical_data\" \n    WHERE \"Id\" = OLD.\"OpticalDataId\"\n)) OR (OLD.\"PhotovoltaicDataId\" IS NOT NULL AND EXISTS (\n    SELECT 1 FROM database.\"photovoltaic_data\" \n    WHERE \"Id\" = OLD.\"PhotovoltaicDataId\"\n))\n) THEN\n    RAISE EXCEPTION 'You cannot delete a data access policy without also deleting the corresponding data.';\nEND IF;\r\nRETURN OLD;\r\nEND;\r\n$LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data$ LANGUAGE plpgsql;\r\nCREATE TRIGGER LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data BEFORE DELETE\r\nON \"database\".\"data_access_policy\"\r\nFOR EACH ROW EXECUTE PROCEDURE \"database\".\"LC_TRIGGER_data_access_policy_can_only_be_deleted_after_data\"();");
        }
    }
}