START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    DROP FUNCTION "database"."LC_TRIGGER_data_id_cannot_change"() CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    DROP FUNCTION "database"."LC_TRIGGER_data_ids_must_match"() CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "CK_GetHttpsResource_Exactly_One_Data_Set";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TYPE database.data_kind ADD VALUE 'life_cycle_data' AFTER 'hygrothermal_data';
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
            CREATE SCHEMA database;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD "LifeCycleDataId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid,
        "Locale" text NOT NULL,
        "ComponentId" uuid NOT NULL,
        "Name" text,
        "Description" text,
        "Warnings" text[] NOT NULL,
        "CreatorId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "AppliedMethod_MethodId" uuid NOT NULL,
        "Approval_Timestamp" timestamp with time zone,
        "Approval_Signature" text,
        "Approval_KeyFingerprint" text,
        "Approval_Query" text,
        "Approval_Variables" jsonb DEFAULT ('{}'),
        "Approval_Message" text,
        "Approval_ApproverId" uuid,
        "DataAccessRights_AllowedUserAndQuantity" jsonb,
        "DataAccessRights_AllowedInstitutions" uuid[],
        "DataAccessRights_AllowedApplications" text[],
        "PublishingState" database.publishing_state NOT NULL,
        CONSTRAINT "PK_lifeCycle_data" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Approvals" (
        "LifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ApproverId" uuid NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Signature" text NOT NULL,
        "KeyFingerprint" text NOT NULL,
        "Query" text NOT NULL,
        "Variables" jsonb NOT NULL DEFAULT ('{}'),
        "Message" text NOT NULL,
        "Statement_Standard_Year" integer,
        "Statement_Standard_Numeration_Prefix" text,
        "Statement_Standard_Numeration_MainNumber" text,
        "Statement_Standard_Numeration_Suffix" text,
        "Statement_Standard_Standardizers" database.standardizer[],
        "Statement_Standard_Locator" text,
        "Statement_Standard_Title" text,
        "Statement_Standard_Abstract" text,
        "Statement_Standard_Section" text,
        "Statement_Publication_Authors" text[],
        "Statement_Publication_Doi" text,
        "Statement_Publication_ArXiv" text,
        "Statement_Publication_Urn" text,
        "Statement_Publication_WebAddress" text,
        "Statement_Publication_Title" text,
        "Statement_Publication_Abstract" text,
        "Statement_Publication_Section" text,
        "Statement_Publication_Exists" boolean,
        "Statement_Exists" boolean NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Approvals" PRIMARY KEY ("LifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Approvals_lifeCycle_data_LifeCycleDataId" FOREIGN KEY ("LifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Arguments" (
        "AppliedMethodLifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Value" jsonb NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Arguments" PRIMARY KEY ("AppliedMethodLifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Arguments_lifeCycle_data_AppliedMethodLifeCy~" FOREIGN KEY ("AppliedMethodLifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Sources" (
        "AppliedMethodLifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Value_DataId" uuid NOT NULL,
        "Value_DataTimestamp" timestamp with time zone NOT NULL,
        "Value_DataKind" database.data_kind NOT NULL,
        "Value_DatabaseId" uuid NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Sources" PRIMARY KEY ("AppliedMethodLifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Sources_lifeCycle_data_AppliedMethodLifeCycl~" FOREIGN KEY ("AppliedMethodLifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_LifeCycleDataId" ON database.get_https_resource ("LifeCycleDataId") WHERE "LifeCycleDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "CK_GetHttpsResource_Exactly_One_Data_Set" CHECK (NUM_NONNULLS("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "LifeCycleDataId", "OpticalDataId", "PhotovoltaicDataId") = 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_lifeCycle_data_LifeCycleDataId" FOREIGN KEY ("LifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_id_cannot_change"() RETURNS trigger as $LC_TRIGGER_data_id_cannot_change$
    BEGIN
      IF COALESCE(OLD."CalorimetricDataId", OLD."GeometricDataId", OLD."HygrothermalDataId", OLD."LifeCycleDataId", OLD."OpticalDataId", OLD."PhotovoltaicDataId") <> COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."LifeCycleDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
    THEN
        RAISE EXCEPTION 'You cannot change the data ID of a resource.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_id_cannot_change$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_id_cannot_change BEFORE UPDATE
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_id_cannot_change"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_ids_must_match"() RETURNS trigger as $LC_TRIGGER_data_ids_must_match$
    BEGIN
      IF NEW."ParentId" IS NOT NULL
       AND (
           SELECT COUNT("Id")
           FROM database."get_https_resource"
           WHERE "Id" = NEW."ParentId" AND COALESCE("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "LifeCycleDataId", "OpticalDataId", "PhotovoltaicDataId") = COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."LifeCycleDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
       )
       <> 1
    THEN
        RAISE EXCEPTION 'The new resource must have the same data ID as its parent.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_ids_must_match$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_ids_must_match BEFORE INSERT
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_ids_must_match"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260316165622_AddLifeCycleData', '10.0.2');
    END IF;
END $EF$;
COMMIT;

