\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20211019125407_InitialCreate') THEN

CREATE SCHEMA IF NOT EXISTS database;

CREATE TYPE public.data_kind AS ENUM ('calorimetric_data', 'hygrothermal_data', 'optical_data', 'photovoltaic_data');
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE database.calorimetric_data (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "GValues" double precision[] NOT NULL,
    "UValues" double precision[] NOT NULL,
    "Locale" text NOT NULL,
    "ComponentId" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Warnings" text[] NOT NULL,
    "CreatorId" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "AppliedMethod_MethodId" uuid NOT NULL,
    CONSTRAINT "PK_calorimetric_data" PRIMARY KEY ("Id")
);

CREATE TABLE database.hygrothermal_data (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Locale" text NOT NULL,
    "ComponentId" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Warnings" text[] NOT NULL,
    "CreatorId" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "AppliedMethod_MethodId" uuid NOT NULL,
    CONSTRAINT "PK_hygrothermal_data" PRIMARY KEY ("Id")
);

CREATE TABLE database.optical_data (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "NearnormalHemisphericalVisibleTransmittances" double precision[] NOT NULL,
    "NearnormalHemisphericalVisibleReflectances" double precision[] NOT NULL,
    "NearnormalHemisphericalSolarTransmittances" double precision[] NOT NULL,
    "NearnormalHemisphericalSolarReflectances" double precision[] NOT NULL,
    "InfraredEmittances" double precision[] NOT NULL,
    "ColorRenderingIndices" double precision[] NOT NULL,
    "Locale" text NOT NULL,
    "ComponentId" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Warnings" text[] NOT NULL,
    "CreatorId" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "AppliedMethod_MethodId" uuid NOT NULL,
    CONSTRAINT "PK_optical_data" PRIMARY KEY ("Id")
);

CREATE TABLE database.photovoltaic_data (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Locale" text NOT NULL,
    "ComponentId" uuid NOT NULL,
    "Name" text NULL,
    "Description" text NULL,
    "Warnings" text[] NOT NULL,
    "CreatorId" uuid NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "AppliedMethod_MethodId" uuid NOT NULL,
    CONSTRAINT "PK_photovoltaic_data" PRIMARY KEY ("Id")
);

CREATE TABLE database."calorimetric_data_Approvals" (
    "CalorimetricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "Signature" text NOT NULL,
    "KeyFingerprint" text NOT NULL,
    "Query" text NOT NULL,
    "Response" text NOT NULL,
    "ApproverId" uuid NOT NULL,
    CONSTRAINT "PK_calorimetric_data_Approvals" PRIMARY KEY ("CalorimetricDataId", "Id"),
    CONSTRAINT "FK_calorimetric_data_Approvals_calorimetric_data_CalorimetricD~" FOREIGN KEY ("CalorimetricDataId") REFERENCES database.calorimetric_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."calorimetric_data_Arguments" (
    "AppliedMethodCalorimetricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_calorimetric_data_Arguments" PRIMARY KEY ("AppliedMethodCalorimetricDataId", "Id"),
    CONSTRAINT "FK_calorimetric_data_Arguments_calorimetric_data_AppliedMethod~" FOREIGN KEY ("AppliedMethodCalorimetricDataId") REFERENCES database.calorimetric_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."calorimetric_data_Sources" (
    "AppliedMethodCalorimetricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value_DataId" uuid NOT NULL,
    "Value_DataTimestamp" timestamp without time zone NOT NULL,
    "Value_DataKind" data_kind NOT NULL,
    "Value_DatabaseId" uuid NOT NULL,
    CONSTRAINT "PK_calorimetric_data_Sources" PRIMARY KEY ("AppliedMethodCalorimetricDataId", "Id"),
    CONSTRAINT "FK_calorimetric_data_Sources_calorimetric_data_AppliedMethodCa~" FOREIGN KEY ("AppliedMethodCalorimetricDataId") REFERENCES database.calorimetric_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."hygrothermal_data_Approvals" (
    "HygrothermalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "Signature" text NOT NULL,
    "KeyFingerprint" text NOT NULL,
    "Query" text NOT NULL,
    "Response" text NOT NULL,
    "ApproverId" uuid NOT NULL,
    CONSTRAINT "PK_hygrothermal_data_Approvals" PRIMARY KEY ("HygrothermalDataId", "Id"),
    CONSTRAINT "FK_hygrothermal_data_Approvals_hygrothermal_data_HygrothermalD~" FOREIGN KEY ("HygrothermalDataId") REFERENCES database.hygrothermal_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."hygrothermal_data_Arguments" (
    "AppliedMethodHygrothermalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_hygrothermal_data_Arguments" PRIMARY KEY ("AppliedMethodHygrothermalDataId", "Id"),
    CONSTRAINT "FK_hygrothermal_data_Arguments_hygrothermal_data_AppliedMethod~" FOREIGN KEY ("AppliedMethodHygrothermalDataId") REFERENCES database.hygrothermal_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."hygrothermal_data_Sources" (
    "AppliedMethodHygrothermalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value_DataId" uuid NOT NULL,
    "Value_DataTimestamp" timestamp without time zone NOT NULL,
    "Value_DataKind" data_kind NOT NULL,
    "Value_DatabaseId" uuid NOT NULL,
    CONSTRAINT "PK_hygrothermal_data_Sources" PRIMARY KEY ("AppliedMethodHygrothermalDataId", "Id"),
    CONSTRAINT "FK_hygrothermal_data_Sources_hygrothermal_data_AppliedMethodHy~" FOREIGN KEY ("AppliedMethodHygrothermalDataId") REFERENCES database.hygrothermal_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."CielabColor" (
    "OpticalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LStar" double precision NOT NULL,
    "AStar" double precision NOT NULL,
    "BStar" double precision NOT NULL,
    CONSTRAINT "PK_CielabColor" PRIMARY KEY ("OpticalDataId", "Id"),
    CONSTRAINT "FK_CielabColor_optical_data_OpticalDataId" FOREIGN KEY ("OpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."optical_data_Approvals" (
    "OpticalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "Signature" text NOT NULL,
    "KeyFingerprint" text NOT NULL,
    "Query" text NOT NULL,
    "Response" text NOT NULL,
    "ApproverId" uuid NOT NULL,
    CONSTRAINT "PK_optical_data_Approvals" PRIMARY KEY ("OpticalDataId", "Id"),
    CONSTRAINT "FK_optical_data_Approvals_optical_data_OpticalDataId" FOREIGN KEY ("OpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."optical_data_Arguments" (
    "AppliedMethodOpticalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_optical_data_Arguments" PRIMARY KEY ("AppliedMethodOpticalDataId", "Id"),
    CONSTRAINT "FK_optical_data_Arguments_optical_data_AppliedMethodOpticalDat~" FOREIGN KEY ("AppliedMethodOpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."optical_data_Sources" (
    "AppliedMethodOpticalDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value_DataId" uuid NOT NULL,
    "Value_DataTimestamp" timestamp without time zone NOT NULL,
    "Value_DataKind" data_kind NOT NULL,
    "Value_DatabaseId" uuid NOT NULL,
    CONSTRAINT "PK_optical_data_Sources" PRIMARY KEY ("AppliedMethodOpticalDataId", "Id"),
    CONSTRAINT "FK_optical_data_Sources_optical_data_AppliedMethodOpticalDataId" FOREIGN KEY ("AppliedMethodOpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database.get_https_resource (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Description" text NOT NULL,
    "HashValue" text NOT NULL,
    "DataFormatId" uuid NOT NULL,
    "CalorimetricDataId" uuid NULL,
    "HygrothermalDataId" uuid NULL,
    "OpticalDataId" uuid NULL,
    "PhotovoltaicDataId" uuid NULL,
    "ParentId" uuid NULL,
    "AppliedConversionMethod_MethodId" uuid NULL,
    "AppliedConversionMethod_SourceName" text NULL,
    CONSTRAINT "PK_get_https_resource" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_get_https_resource_calorimetric_data_CalorimetricDataId" FOREIGN KEY ("CalorimetricDataId") REFERENCES database.calorimetric_data ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_get_https_resource_get_https_resource_ParentId" FOREIGN KEY ("ParentId") REFERENCES database.get_https_resource ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_get_https_resource_hygrothermal_data_HygrothermalDataId" FOREIGN KEY ("HygrothermalDataId") REFERENCES database.hygrothermal_data ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_get_https_resource_optical_data_OpticalDataId" FOREIGN KEY ("OpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_get_https_resource_photovoltaic_data_PhotovoltaicDataId" FOREIGN KEY ("PhotovoltaicDataId") REFERENCES database.photovoltaic_data ("Id") ON DELETE RESTRICT
);

CREATE TABLE database."photovoltaic_data_Approvals" (
    "PhotovoltaicDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp without time zone NOT NULL,
    "Signature" text NOT NULL,
    "KeyFingerprint" text NOT NULL,
    "Query" text NOT NULL,
    "Response" text NOT NULL,
    "ApproverId" uuid NOT NULL,
    CONSTRAINT "PK_photovoltaic_data_Approvals" PRIMARY KEY ("PhotovoltaicDataId", "Id"),
    CONSTRAINT "FK_photovoltaic_data_Approvals_photovoltaic_data_PhotovoltaicD~" FOREIGN KEY ("PhotovoltaicDataId") REFERENCES database.photovoltaic_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."photovoltaic_data_Arguments" (
    "AppliedMethodPhotovoltaicDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_photovoltaic_data_Arguments" PRIMARY KEY ("AppliedMethodPhotovoltaicDataId", "Id"),
    CONSTRAINT "FK_photovoltaic_data_Arguments_photovoltaic_data_AppliedMethod~" FOREIGN KEY ("AppliedMethodPhotovoltaicDataId") REFERENCES database.photovoltaic_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."photovoltaic_data_Sources" (
    "AppliedMethodPhotovoltaicDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value_DataId" uuid NOT NULL,
    "Value_DataTimestamp" timestamp without time zone NOT NULL,
    "Value_DataKind" data_kind NOT NULL,
    "Value_DatabaseId" uuid NOT NULL,
    CONSTRAINT "PK_photovoltaic_data_Sources" PRIMARY KEY ("AppliedMethodPhotovoltaicDataId", "Id"),
    CONSTRAINT "FK_photovoltaic_data_Sources_photovoltaic_data_AppliedMethodPh~" FOREIGN KEY ("AppliedMethodPhotovoltaicDataId") REFERENCES database.photovoltaic_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."FileMetaInformation" (
    "GetHttpsResourceId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Path" text[] NOT NULL,
    "DataFormatId" uuid NOT NULL,
    CONSTRAINT "PK_FileMetaInformation" PRIMARY KEY ("GetHttpsResourceId", "Id"),
    CONSTRAINT "FK_FileMetaInformation_get_https_resource_GetHttpsResourceId" FOREIGN KEY ("GetHttpsResourceId") REFERENCES database.get_https_resource ("Id") ON DELETE CASCADE
);

CREATE TABLE database."get_https_resource_Arguments" (
    "ToTreeVertexAppliedConversionMethodGetHttpsResourceId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_get_https_resource_Arguments" PRIMARY KEY ("ToTreeVertexAppliedConversionMethodGetHttpsResourceId", "Id"),
    CONSTRAINT "FK_get_https_resource_Arguments_get_https_resource_ToTreeVerte~" FOREIGN KEY ("ToTreeVertexAppliedConversionMethodGetHttpsResourceId") REFERENCES database.get_https_resource ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_get_https_resource_CalorimetricDataId" ON database.get_https_resource ("CalorimetricDataId");

CREATE INDEX "IX_get_https_resource_HygrothermalDataId" ON database.get_https_resource ("HygrothermalDataId");

CREATE INDEX "IX_get_https_resource_OpticalDataId" ON database.get_https_resource ("OpticalDataId");

CREATE INDEX "IX_get_https_resource_ParentId" ON database.get_https_resource ("ParentId");

CREATE INDEX "IX_get_https_resource_PhotovoltaicDataId" ON database.get_https_resource ("PhotovoltaicDataId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211019125407_InitialCreate', '5.0.10');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230126153325_RenameXminToVersion') THEN

ALTER TABLE database."photovoltaic_data_Sources" ALTER COLUMN "Value_DataTimestamp" TYPE timestamp with time zone;

ALTER TABLE database."photovoltaic_data_Approvals" ALTER COLUMN "Timestamp" TYPE timestamp with time zone;

ALTER TABLE database.photovoltaic_data ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE database."optical_data_Sources" ALTER COLUMN "Value_DataTimestamp" TYPE timestamp with time zone;

ALTER TABLE database."optical_data_Approvals" ALTER COLUMN "Timestamp" TYPE timestamp with time zone;

ALTER TABLE database.optical_data ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE database."hygrothermal_data_Sources" ALTER COLUMN "Value_DataTimestamp" TYPE timestamp with time zone;

ALTER TABLE database."hygrothermal_data_Approvals" ALTER COLUMN "Timestamp" TYPE timestamp with time zone;

ALTER TABLE database.hygrothermal_data ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE database."calorimetric_data_Sources" ALTER COLUMN "Value_DataTimestamp" TYPE timestamp with time zone;

ALTER TABLE database."calorimetric_data_Approvals" ALTER COLUMN "Timestamp" TYPE timestamp with time zone;

ALTER TABLE database.calorimetric_data ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230126153325_RenameXminToVersion', '7.0.2');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230210135413_AddDataProtectionKeys') THEN

CREATE TABLE database."DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text NULL,
    "Xml" text NULL,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230210135413_AddDataProtectionKeys', '7.0.2');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230420143838_OpenIddict') THEN

CREATE TABLE database."OpenIddictApplications" (
    "Id" text NOT NULL,
    "ClientId" character varying(100),
    "ClientSecret" text,
    "ConcurrencyToken" character varying(50),
    "ConsentType" character varying(50),
    "DisplayName" text,
    "DisplayNames" text,
    "Permissions" text,
    "PostLogoutRedirectUris" text,
    "Properties" text,
    "RedirectUris" text,
    "Requirements" text,
    "Type" character varying(50),
    CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY ("Id")
);

CREATE TABLE database."OpenIddictScopes" (
    "Id" text NOT NULL,
    "ConcurrencyToken" character varying(50),
    "Description" text,
    "Descriptions" text,
    "DisplayName" text,
    "DisplayNames" text,
    "Name" character varying(200),
    "Properties" text,
    "Resources" text,
    CONSTRAINT "PK_OpenIddictScopes" PRIMARY KEY ("Id")
);

CREATE TABLE database."OpenIddictAuthorizations" (
    "Id" text NOT NULL,
    "ApplicationId" text,
    "ConcurrencyToken" character varying(50),
    "CreationDate" timestamp with time zone,
    "Properties" text,
    "Scopes" text,
    "Status" character varying(50),
    "Subject" character varying(400),
    "Type" character varying(50),
    CONSTRAINT "PK_OpenIddictAuthorizations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpenIddictAuthorizations_OpenIddictApplications_Application~" FOREIGN KEY ("ApplicationId") REFERENCES database."OpenIddictApplications" ("Id")
);

CREATE TABLE database."OpenIddictTokens" (
    "Id" text NOT NULL,
    "ApplicationId" text,
    "AuthorizationId" text,
    "ConcurrencyToken" character varying(50),
    "CreationDate" timestamp with time zone,
    "ExpirationDate" timestamp with time zone,
    "Payload" text,
    "Properties" text,
    "RedemptionDate" timestamp with time zone,
    "ReferenceId" character varying(100),
    "Status" character varying(50),
    "Subject" character varying(400),
    "Type" character varying(50),
    CONSTRAINT "PK_OpenIddictTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OpenIddictTokens_OpenIddictApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES database."OpenIddictApplications" ("Id"),
    CONSTRAINT "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId" FOREIGN KEY ("AuthorizationId") REFERENCES database."OpenIddictAuthorizations" ("Id")
);

CREATE UNIQUE INDEX "IX_OpenIddictApplications_ClientId" ON database."OpenIddictApplications" ("ClientId");

CREATE INDEX "IX_OpenIddictAuthorizations_ApplicationId_Status_Subject_Type" ON database."OpenIddictAuthorizations" ("ApplicationId", "Status", "Subject", "Type");

CREATE UNIQUE INDEX "IX_OpenIddictScopes_Name" ON database."OpenIddictScopes" ("Name");

CREATE INDEX "IX_OpenIddictTokens_ApplicationId_Status_Subject_Type" ON database."OpenIddictTokens" ("ApplicationId", "Status", "Subject", "Type");

CREATE INDEX "IX_OpenIddictTokens_AuthorizationId" ON database."OpenIddictTokens" ("AuthorizationId");

CREATE UNIQUE INDEX "IX_OpenIddictTokens_ReferenceId" ON database."OpenIddictTokens" ("ReferenceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230420143838_OpenIddict', '8.0.6');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230427133946_CreateUserTable') THEN

CREATE TABLE database."user" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Subject" text NOT NULL,
    "Email" text NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_user" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230427133946_CreateUserTable', '8.0.6');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240522120225_UpgradeOpenIddict') THEN

ALTER TABLE database."user" DROP COLUMN "Email";

ALTER TABLE database."OpenIddictApplications" RENAME COLUMN "Type" TO "ClientType";

ALTER TABLE database."OpenIddictApplications" ADD "ApplicationType" character varying(50);

ALTER TABLE database."OpenIddictApplications" ADD "JsonWebKeySet" text;

ALTER TABLE database."OpenIddictApplications" ADD "Settings" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240522120225_UpgradeOpenIddict', '8.0.6');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240709144935_AddStatementToDataApproval') THEN

CREATE TYPE public.standardizer AS ENUM ('aerc', 'agi', 'ashrae', 'breeam', 'bs', 'bsi', 'cen', 'cie', 'dgnb', 'din', 'dvwg', 'iec', 'ies', 'ift', 'iso', 'jis', 'leed', 'nfrc', 'riba', 'ul', 'unece', 'vdi', 'vff', 'well');
DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Abstract" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_ArXiv" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Authors" text[];

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Doi" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Section" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Title" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_Urn" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Publication_WebAddress" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Abstract" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Locator" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Numeration_MainNumber" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Numeration_Prefix" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Numeration_Suffix" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Section" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Standardizers" standardizer[];

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Title" text;

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Standard_Year" integer;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Abstract" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_ArXiv" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Authors" text[];

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Doi" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Section" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Title" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_Urn" text;

ALTER TABLE database."optical_data_Approvals" ADD "Publication_WebAddress" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Abstract" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Locator" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Numeration_MainNumber" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Numeration_Prefix" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Numeration_Suffix" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Section" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Standardizers" standardizer[];

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Title" text;

ALTER TABLE database."optical_data_Approvals" ADD "Standard_Year" integer;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Abstract" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_ArXiv" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Authors" text[];

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Doi" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Section" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Title" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_Urn" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Publication_WebAddress" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Abstract" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Locator" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Numeration_MainNumber" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Numeration_Prefix" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Numeration_Suffix" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Section" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Standardizers" standardizer[];

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Title" text;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Standard_Year" integer;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Abstract" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_ArXiv" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Authors" text[];

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Doi" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Section" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Title" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_Urn" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Publication_WebAddress" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Abstract" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Locator" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Numeration_MainNumber" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Numeration_Prefix" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Numeration_Suffix" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Section" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Standardizers" standardizer[];

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Title" text;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Standard_Year" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240709144935_AddStatementToDataApproval', '8.0.6');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240722133619_MoveEnumTypesToMetabaseSchema') THEN

DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE TYPE database.data_kind AS ENUM ('calorimetric_data', 'hygrothermal_data', 'optical_data', 'photovoltaic_data');
DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE TYPE database.standardizer AS ENUM ('aerc', 'agi', 'ashrae', 'breeam', 'bs', 'bsi', 'cen', 'cie', 'dgnb', 'din', 'dvwg', 'iec', 'ies', 'ift', 'iso', 'jis', 'leed', 'nfrc', 'riba', 'ul', 'unece', 'vdi', 'vff', 'well');

DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE database."photovoltaic_data_Sources" ALTER COLUMN "Value_DataKind" TYPE database.data_kind USING "Value_DataKind"::text::database.data_kind;

ALTER TABLE database."photovoltaic_data_Approvals" ALTER COLUMN "Standard_Standardizers" TYPE database.standardizer[] USING "Standard_Standardizers"::text::database.standardizer[];

ALTER TABLE database."optical_data_Sources" ALTER COLUMN "Value_DataKind" TYPE database.data_kind USING "Value_DataKind"::text::database.data_kind;

ALTER TABLE database."optical_data_Approvals" ALTER COLUMN "Standard_Standardizers" TYPE database.standardizer[] USING "Standard_Standardizers"::text::database.standardizer[];

ALTER TABLE database."hygrothermal_data_Sources" ALTER COLUMN "Value_DataKind" TYPE database.data_kind USING "Value_DataKind"::text::database.data_kind;

ALTER TABLE database."hygrothermal_data_Approvals" ALTER COLUMN "Standard_Standardizers" TYPE database.standardizer[] USING "Standard_Standardizers"::text::database.standardizer[];

ALTER TABLE database."calorimetric_data_Sources" ALTER COLUMN "Value_DataKind" TYPE database.data_kind USING "Value_DataKind"::text::database.data_kind;

ALTER TABLE database."calorimetric_data_Approvals" ALTER COLUMN "Standard_Standardizers" TYPE database.standardizer[] USING "Standard_Standardizers"::text::database.standardizer[];

DROP TYPE public.data_kind;
DROP TYPE public.standardizer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240722133619_MoveEnumTypesToMetabaseSchema', '8.0.6');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240917073732_AddGeometricData') THEN

ALTER TYPE database.data_kind ADD VALUE 'geometric_data';

ALTER TABLE database.get_https_resource ADD "GeometricDataId" uuid;

CREATE TABLE database.geometric_data (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Thicknesses" double precision[] NOT NULL,
    "Locale" text NOT NULL,
    "ComponentId" uuid NOT NULL,
    "Name" text,
    "Description" text,
    "Warnings" text[] NOT NULL,
    "CreatorId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AppliedMethod_MethodId" uuid NOT NULL,
    CONSTRAINT "PK_geometric_data" PRIMARY KEY ("Id")
);

CREATE TABLE database."geometric_data_Approvals" (
    "GeometricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApproverId" uuid NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Signature" text NOT NULL,
    "KeyFingerprint" text NOT NULL,
    "Query" text NOT NULL,
    "Response" text NOT NULL,
    "Publication_Authors" text[],
    "Publication_Doi" text,
    "Publication_ArXiv" text,
    "Publication_Urn" text,
    "Publication_WebAddress" text,
    "Publication_Title" text,
    "Publication_Abstract" text,
    "Publication_Section" text,
    "Standard_Year" integer,
    "Standard_Numeration_Prefix" text,
    "Standard_Numeration_MainNumber" text,
    "Standard_Numeration_Suffix" text,
    "Standard_Standardizers" database.standardizer[],
    "Standard_Locator" text,
    "Standard_Title" text,
    "Standard_Abstract" text,
    "Standard_Section" text,
    CONSTRAINT "PK_geometric_data_Approvals" PRIMARY KEY ("GeometricDataId", "Id"),
    CONSTRAINT "FK_geometric_data_Approvals_geometric_data_GeometricDataId" FOREIGN KEY ("GeometricDataId") REFERENCES database.geometric_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."geometric_data_Arguments" (
    "AppliedMethodGeometricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" jsonb NOT NULL,
    CONSTRAINT "PK_geometric_data_Arguments" PRIMARY KEY ("AppliedMethodGeometricDataId", "Id"),
    CONSTRAINT "FK_geometric_data_Arguments_geometric_data_AppliedMethodGeomet~" FOREIGN KEY ("AppliedMethodGeometricDataId") REFERENCES database.geometric_data ("Id") ON DELETE CASCADE
);

CREATE TABLE database."geometric_data_Sources" (
    "AppliedMethodGeometricDataId" uuid NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value_DataId" uuid NOT NULL,
    "Value_DataTimestamp" timestamp with time zone NOT NULL,
    "Value_DataKind" database.data_kind NOT NULL,
    "Value_DatabaseId" uuid NOT NULL,
    CONSTRAINT "PK_geometric_data_Sources" PRIMARY KEY ("AppliedMethodGeometricDataId", "Id"),
    CONSTRAINT "FK_geometric_data_Sources_geometric_data_AppliedMethodGeometri~" FOREIGN KEY ("AppliedMethodGeometricDataId") REFERENCES database.geometric_data ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_get_https_resource_GeometricDataId" ON database.get_https_resource ("GeometricDataId");

ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_geometric_data_GeometricDataId" FOREIGN KEY ("GeometricDataId") REFERENCES database.geometric_data ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240917073732_AddGeometricData', '8.0.8');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250129163501_UpgradeToNet9') THEN

ALTER TABLE database."geometric_data_Sources" ALTER COLUMN "Value_DataKind" TYPE database.data_kind;

ALTER TABLE database."geometric_data_Approvals" ALTER COLUMN "Standard_Standardizers" TYPE database.standardizer[];

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250129163501_UpgradeToNet9', '9.0.1');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250213155333_AddTypeSubtypeAndCoatedSideToData') THEN

DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE TYPE database.coated_side AS ENUM ('back', 'both', 'front', 'neither');
DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE TYPE database.optical_component_subtype AS ENUM ('acid_etched_glass', 'applied_film', 'cellular_shade', 'chromogenic', 'coated', 'coating', 'diffusing_shade', 'embedded_coating', 'film', 'fritted_glass', 'interlayer', 'laminate', 'monolithic', 'perforated_screen', 'pleated_shade', 'roller_shade', 'roman_shade', 'sandblasted_glass', 'shade_material', 'venetian_blind', 'vertical_louver', 'woven_shade');
DO $X$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
        CREATE SCHEMA database;
    END IF;
END $X$;

CREATE TYPE database.optical_component_type AS ENUM ('glazing', 'shading');

ALTER TABLE database.optical_data ADD "CoatedSide" database.coated_side;

ALTER TABLE database.optical_data ADD "Subtype" database.optical_component_subtype;

ALTER TABLE database.optical_data ADD "Type" database.optical_component_type;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250213155333_AddTypeSubtypeAndCoatedSideToData', '9.0.1');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218172859_MakeDescriptionOptional') THEN

ALTER TABLE database.get_https_resource ALTER COLUMN "Description" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250218172859_MakeDescriptionOptional', '9.0.1');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250331141152_AddAccessRights') THEN

ALTER TABLE database.photovoltaic_data ADD "Approval_KeyFingerprint" text;

ALTER TABLE database.photovoltaic_data ADD "Approval_Query" text;

ALTER TABLE database.photovoltaic_data ADD "Approval_Response" text;

ALTER TABLE database.photovoltaic_data ADD "Approval_Signature" text;

ALTER TABLE database.photovoltaic_data ADD "Approval_Timestamp" timestamp with time zone;

ALTER TABLE database.optical_data ADD "Approval_KeyFingerprint" text;

ALTER TABLE database.optical_data ADD "Approval_Query" text;

ALTER TABLE database.optical_data ADD "Approval_Response" text;

ALTER TABLE database.optical_data ADD "Approval_Signature" text;

ALTER TABLE database.optical_data ADD "Approval_Timestamp" timestamp with time zone;

ALTER TABLE database.hygrothermal_data ADD "Approval_KeyFingerprint" text;

ALTER TABLE database.hygrothermal_data ADD "Approval_Query" text;

ALTER TABLE database.hygrothermal_data ADD "Approval_Response" text;

ALTER TABLE database.hygrothermal_data ADD "Approval_Signature" text;

ALTER TABLE database.hygrothermal_data ADD "Approval_Timestamp" timestamp with time zone;

ALTER TABLE database.geometric_data ADD "Approval_KeyFingerprint" text;

ALTER TABLE database.geometric_data ADD "Approval_Query" text;

ALTER TABLE database.geometric_data ADD "Approval_Response" text;

ALTER TABLE database.geometric_data ADD "Approval_Signature" text;

ALTER TABLE database.geometric_data ADD "Approval_Timestamp" timestamp with time zone;

ALTER TABLE database.calorimetric_data ADD "Approval_KeyFingerprint" text;

ALTER TABLE database.calorimetric_data ADD "Approval_Query" text;

ALTER TABLE database.calorimetric_data ADD "Approval_Response" text;

ALTER TABLE database.calorimetric_data ADD "Approval_Signature" text;

ALTER TABLE database.calorimetric_data ADD "Approval_Timestamp" timestamp with time zone;

CREATE TABLE database.access_rights (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "InstitutionId" uuid NOT NULL,
    "AllowedUserCount" bigint,
    "AllowedDatasetsPerTime" bigint,
    "Period" interval NOT NULL,
    "UserAlreadyAccessed" uuid[] NOT NULL,
    CONSTRAINT "PK_access_rights" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250331141152_AddAccessRights', '9.0.5');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250527144412_AddDataAccessRights') THEN

ALTER TABLE database.photovoltaic_data ADD "DataAccessRights_AllowedApplications" text[];

ALTER TABLE database.photovoltaic_data ADD "DataAccessRights_AllowedInstitutions" uuid[];

ALTER TABLE database.photovoltaic_data ADD "DataAccessRights_AllowedUserAndQuantity" jsonb;

ALTER TABLE database.optical_data ADD "DataAccessRights_AllowedApplications" text[];

ALTER TABLE database.optical_data ADD "DataAccessRights_AllowedInstitutions" uuid[];

ALTER TABLE database.optical_data ADD "DataAccessRights_AllowedUserAndQuantity" jsonb;

ALTER TABLE database.hygrothermal_data ADD "DataAccessRights_AllowedApplications" text[];

ALTER TABLE database.hygrothermal_data ADD "DataAccessRights_AllowedInstitutions" uuid[];

ALTER TABLE database.hygrothermal_data ADD "DataAccessRights_AllowedUserAndQuantity" jsonb;

ALTER TABLE database.geometric_data ADD "DataAccessRights_AllowedApplications" text[];

ALTER TABLE database.geometric_data ADD "DataAccessRights_AllowedInstitutions" uuid[];

ALTER TABLE database.geometric_data ADD "DataAccessRights_AllowedUserAndQuantity" jsonb;

ALTER TABLE database.calorimetric_data ADD "DataAccessRights_AllowedApplications" text[];

ALTER TABLE database.calorimetric_data ADD "DataAccessRights_AllowedInstitutions" uuid[];

ALTER TABLE database.calorimetric_data ADD "DataAccessRights_AllowedUserAndQuantity" jsonb;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250527144412_AddDataAccessRights', '9.0.5');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250527150325_MoveInstitutionAccessRights') THEN

ALTER TABLE database.access_rights DROP CONSTRAINT "PK_access_rights";

ALTER TABLE database.access_rights RENAME TO institution_access_rights;

ALTER TABLE database.institution_access_rights ADD CONSTRAINT "PK_institution_access_rights" PRIMARY KEY ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250527150325_MoveInstitutionAccessRights', '9.0.5');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250530151605_ModelReferenceProperly') THEN

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Year" TO "Statement_Standard_Year";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Title" TO "Statement_Standard_Title";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Standardizers" TO "Statement_Standard_Standardizers";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Section" TO "Statement_Standard_Section";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Numeration_Suffix" TO "Statement_Standard_Numeration_Suffix";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Numeration_Prefix" TO "Statement_Standard_Numeration_Prefix";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Numeration_MainNumber" TO "Statement_Standard_Numeration_MainNumber";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Locator" TO "Statement_Standard_Locator";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Standard_Abstract" TO "Statement_Standard_Abstract";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_WebAddress" TO "Statement_Publication_WebAddress";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Urn" TO "Statement_Publication_Urn";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Title" TO "Statement_Publication_Title";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Section" TO "Statement_Publication_Section";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Doi" TO "Statement_Publication_Doi";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Authors" TO "Statement_Publication_Authors";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_ArXiv" TO "Statement_Publication_ArXiv";

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Publication_Abstract" TO "Statement_Publication_Abstract";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Year" TO "Statement_Standard_Year";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Title" TO "Statement_Standard_Title";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Standardizers" TO "Statement_Standard_Standardizers";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Section" TO "Statement_Standard_Section";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Numeration_Suffix" TO "Statement_Standard_Numeration_Suffix";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Numeration_Prefix" TO "Statement_Standard_Numeration_Prefix";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Numeration_MainNumber" TO "Statement_Standard_Numeration_MainNumber";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Locator" TO "Statement_Standard_Locator";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Standard_Abstract" TO "Statement_Standard_Abstract";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_WebAddress" TO "Statement_Publication_WebAddress";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Urn" TO "Statement_Publication_Urn";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Title" TO "Statement_Publication_Title";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Section" TO "Statement_Publication_Section";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Doi" TO "Statement_Publication_Doi";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Authors" TO "Statement_Publication_Authors";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_ArXiv" TO "Statement_Publication_ArXiv";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Publication_Abstract" TO "Statement_Publication_Abstract";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Year" TO "Statement_Standard_Year";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Title" TO "Statement_Standard_Title";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Standardizers" TO "Statement_Standard_Standardizers";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Section" TO "Statement_Standard_Section";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Numeration_Suffix" TO "Statement_Standard_Numeration_Suffix";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Numeration_Prefix" TO "Statement_Standard_Numeration_Prefix";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Numeration_MainNumber" TO "Statement_Standard_Numeration_MainNumber";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Locator" TO "Statement_Standard_Locator";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Standard_Abstract" TO "Statement_Standard_Abstract";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_WebAddress" TO "Statement_Publication_WebAddress";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Urn" TO "Statement_Publication_Urn";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Title" TO "Statement_Publication_Title";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Section" TO "Statement_Publication_Section";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Doi" TO "Statement_Publication_Doi";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Authors" TO "Statement_Publication_Authors";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_ArXiv" TO "Statement_Publication_ArXiv";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Publication_Abstract" TO "Statement_Publication_Abstract";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Year" TO "Statement_Standard_Year";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Title" TO "Statement_Standard_Title";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Standardizers" TO "Statement_Standard_Standardizers";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Section" TO "Statement_Standard_Section";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Numeration_Suffix" TO "Statement_Standard_Numeration_Suffix";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Numeration_Prefix" TO "Statement_Standard_Numeration_Prefix";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Numeration_MainNumber" TO "Statement_Standard_Numeration_MainNumber";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Locator" TO "Statement_Standard_Locator";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Standard_Abstract" TO "Statement_Standard_Abstract";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_WebAddress" TO "Statement_Publication_WebAddress";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Urn" TO "Statement_Publication_Urn";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Title" TO "Statement_Publication_Title";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Section" TO "Statement_Publication_Section";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Doi" TO "Statement_Publication_Doi";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Authors" TO "Statement_Publication_Authors";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_ArXiv" TO "Statement_Publication_ArXiv";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Publication_Abstract" TO "Statement_Publication_Abstract";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Year" TO "Statement_Standard_Year";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Title" TO "Statement_Standard_Title";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Standardizers" TO "Statement_Standard_Standardizers";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Section" TO "Statement_Standard_Section";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Numeration_Suffix" TO "Statement_Standard_Numeration_Suffix";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Numeration_Prefix" TO "Statement_Standard_Numeration_Prefix";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Numeration_MainNumber" TO "Statement_Standard_Numeration_MainNumber";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Locator" TO "Statement_Standard_Locator";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Standard_Abstract" TO "Statement_Standard_Abstract";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_WebAddress" TO "Statement_Publication_WebAddress";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Urn" TO "Statement_Publication_Urn";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Title" TO "Statement_Publication_Title";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Section" TO "Statement_Publication_Section";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Doi" TO "Statement_Publication_Doi";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Authors" TO "Statement_Publication_Authors";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_ArXiv" TO "Statement_Publication_ArXiv";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Publication_Abstract" TO "Statement_Publication_Abstract";

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Statement_Exists" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE database."optical_data_Approvals" ADD "Statement_Exists" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Statement_Exists" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE database."geometric_data_Approvals" ADD "Statement_Exists" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Statement_Exists" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530151605_ModelReferenceProperly', '9.0.5');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250530155318_AddRequiredPropertyExistsToPublication') THEN

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Statement_Publication_Exists" boolean;

ALTER TABLE database."optical_data_Approvals" ADD "Statement_Publication_Exists" boolean;

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Statement_Publication_Exists" boolean;

ALTER TABLE database."geometric_data_Approvals" ADD "Statement_Publication_Exists" boolean;

ALTER TABLE database."calorimetric_data_Approvals" ADD "Statement_Publication_Exists" boolean;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530155318_AddRequiredPropertyExistsToPublication', '9.0.5');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725172127_UpgradeOpenIddictToVersion7') THEN

ALTER TABLE database."OpenIddictTokens" ALTER COLUMN "Type" TYPE character varying(150);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250725172127_UpgradeOpenIddictToVersion7', '9.0.7');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250731163636_MakeInstitutionIdOfAccessRightsUnique') THEN

CREATE UNIQUE INDEX "IX_institution_access_rights_InstitutionId" ON database.institution_access_rights ("InstitutionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250731163636_MakeInstitutionIdOfAccessRightsUnique', '9.0.7');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812171810_AddQueryVariablesToApprovals') THEN

ALTER TABLE database."photovoltaic_data_Approvals" ADD "Variables" jsonb NOT NULL DEFAULT ('{}');

ALTER TABLE database.photovoltaic_data ADD "Approval_Variables" jsonb DEFAULT ('{}');

ALTER TABLE database."optical_data_Approvals" ADD "Variables" jsonb NOT NULL DEFAULT ('{}');

ALTER TABLE database.optical_data ADD "Approval_Variables" jsonb DEFAULT ('{}');

ALTER TABLE database."hygrothermal_data_Approvals" ADD "Variables" jsonb NOT NULL DEFAULT ('{}');

ALTER TABLE database.hygrothermal_data ADD "Approval_Variables" jsonb DEFAULT ('{}');

ALTER TABLE database."geometric_data_Approvals" ADD "Variables" jsonb NOT NULL DEFAULT ('{}');

ALTER TABLE database.geometric_data ADD "Approval_Variables" jsonb DEFAULT ('{}');

ALTER TABLE database."calorimetric_data_Approvals" ADD "Variables" jsonb NOT NULL DEFAULT ('{}');

ALTER TABLE database.calorimetric_data ADD "Approval_Variables" jsonb DEFAULT ('{}');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250812171810_AddQueryVariablesToApprovals', '9.0.8');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250902122837_RenameResponsePropertyOfApprovalsToMessage') THEN

ALTER TABLE database."photovoltaic_data_Approvals" RENAME COLUMN "Response" TO "Message";

ALTER TABLE database.photovoltaic_data RENAME COLUMN "Approval_Response" TO "Approval_Message";

ALTER TABLE database."optical_data_Approvals" RENAME COLUMN "Response" TO "Message";

ALTER TABLE database.optical_data RENAME COLUMN "Approval_Response" TO "Approval_Message";

ALTER TABLE database."hygrothermal_data_Approvals" RENAME COLUMN "Response" TO "Message";

ALTER TABLE database.hygrothermal_data RENAME COLUMN "Approval_Response" TO "Approval_Message";

ALTER TABLE database."geometric_data_Approvals" RENAME COLUMN "Response" TO "Message";

ALTER TABLE database.geometric_data RENAME COLUMN "Approval_Response" TO "Approval_Message";

ALTER TABLE database."calorimetric_data_Approvals" RENAME COLUMN "Response" TO "Message";

ALTER TABLE database.calorimetric_data RENAME COLUMN "Approval_Response" TO "Approval_Message";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250902122837_RenameResponsePropertyOfApprovalsToMessage', '9.0.8');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907130041_AddApproverIdToResponseApproval') THEN

ALTER TABLE database.photovoltaic_data ADD "Approval_ApproverId" uuid;

ALTER TABLE database.optical_data ADD "Approval_ApproverId" uuid;

ALTER TABLE database.hygrothermal_data ADD "Approval_ApproverId" uuid;

ALTER TABLE database.geometric_data ADD "Approval_ApproverId" uuid;

ALTER TABLE database.calorimetric_data ADD "Approval_ApproverId" uuid;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250907130041_AddApproverIdToResponseApproval', '9.0.8');

    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010164110_UpdateCoatedSideEnumeration') THEN

        ALTER TYPE database.coated_side RENAME TO coated_side_old;
        CREATE TYPE database.coated_side AS ENUM ('back', 'both', 'front', 'neither');
        ALTER TABLE database.optical_data ALTER COLUMN "CoatedSide" TYPE database.coated_side USING "CoatedSide"::text::database.coated_side;
        DROP TYPE database.coated_side_old;

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20251010164110_UpdateCoatedSideEnumeration', '9.0.8');

    END IF;
END $EF$;

COMMIT;
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    ALTER TABLE database.photovoltaic_data ADD "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    ALTER TABLE database.optical_data ADD "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    ALTER TABLE database.hygrothermal_data ADD "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    ALTER TABLE database.geometric_data ADD "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    ALTER TABLE database.calorimetric_data ADD "UserId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251023152609_RememberUserWhoCreatedDataSet') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251023152609_RememberUserWhoCreatedDataSet', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
            CREATE SCHEMA database;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    CREATE TYPE database.calorimetric_observer AS ENUM ('ten_degrees', 'two_degrees');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    CREATE TYPE database.illuminant AS ENUM ('a', 'd65');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    ALTER TABLE database."optical_data_Approvals" ALTER COLUMN "Variables" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    ALTER TABLE database.optical_data ALTER COLUMN "Approval_Variables" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    ALTER TABLE database."CielabColor" ADD "Illuminant" database.illuminant;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    ALTER TABLE database."CielabColor" ADD "Observer" database.calorimetric_observer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    ALTER TABLE database."CielabColor" ADD CONSTRAINT "CK_OpticalData_CielabColors_LStar" CHECK ("LStar" >= 0.0 AND "LStar" <= 100.0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251024124734_AddObserverAndIlluminantToCielabColor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251024124734_AddObserverAndIlluminantToCielabColor', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    CREATE TYPE database.publishing_state AS ENUM ('pending', 'published', 'retracted');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    ALTER TABLE database.photovoltaic_data ADD "PublishingState" database.publishing_state NOT NULL DEFAULT 'pending'::database.publishing_state;
    UPDATE database.photovoltaic_data SET "PublishingState" = 'published';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    ALTER TABLE database.optical_data ADD "PublishingState" database.publishing_state NOT NULL DEFAULT 'pending'::database.publishing_state;
    UPDATE database.optical_data SET "PublishingState" = 'published';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    ALTER TABLE database.hygrothermal_data ADD "PublishingState" database.publishing_state NOT NULL DEFAULT 'pending'::database.publishing_state;
    UPDATE database.hygrothermal_data SET "PublishingState" = 'published';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    ALTER TABLE database.geometric_data ADD "PublishingState" database.publishing_state NOT NULL DEFAULT 'pending'::database.publishing_state;
    UPDATE database.geometric_data SET "PublishingState" = 'published';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    ALTER TABLE database.calorimetric_data ADD "PublishingState" database.publishing_state NOT NULL DEFAULT 'pending'::database.publishing_state;
    UPDATE database.calorimetric_data SET "PublishingState" = 'published';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251030170839_AddPublishingStateToDataSets') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251030170839_AddPublishingStateToDataSets', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031125736_AddFileExtensionToResource') THEN
    ALTER TABLE database.get_https_resource ADD "FileExtension" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031125736_AddFileExtensionToResource') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251031125736_AddFileExtensionToResource', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "FK_get_https_resource_calorimetric_data_CalorimetricDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "FK_get_https_resource_geometric_data_GeometricDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "FK_get_https_resource_hygrothermal_data_HygrothermalDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "FK_get_https_resource_optical_data_OpticalDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "FK_get_https_resource_photovoltaic_data_PhotovoltaicDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    DROP INDEX database."IX_get_https_resource_CalorimetricDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    DROP INDEX database."IX_get_https_resource_GeometricDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    DROP INDEX database."IX_get_https_resource_HygrothermalDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    DROP INDEX database."IX_get_https_resource_OpticalDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    DROP INDEX database."IX_get_https_resource_PhotovoltaicDataId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.photovoltaic_data ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database."optical_data_Approvals" ALTER COLUMN "Variables" SET DEFAULT ('{}');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.optical_data ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.optical_data ALTER COLUMN "Approval_Variables" SET DEFAULT ('{}');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.hygrothermal_data ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.geometric_data ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.calorimetric_data ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_CalorimetricDataId" ON database.get_https_resource ("CalorimetricDataId") WHERE "CalorimetricDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_GeometricDataId" ON database.get_https_resource ("GeometricDataId") WHERE "GeometricDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_HygrothermalDataId" ON database.get_https_resource ("HygrothermalDataId") WHERE "HygrothermalDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_OpticalDataId" ON database.get_https_resource ("OpticalDataId") WHERE "OpticalDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_PhotovoltaicDataId" ON database.get_https_resource ("PhotovoltaicDataId") WHERE "PhotovoltaicDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "CK_GetHttpsResource_Exactly_One_Data_Set" CHECK (NUM_NONNULLS("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "OpticalDataId", "PhotovoltaicDataId") = 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "CK_GetHttpsResource_Root_Or_Child" CHECK (("ParentId" IS NULL AND "AppliedConversionMethod_MethodId" IS NULL)
    OR ("ParentId" IS NOT NULL AND "AppliedConversionMethod_MethodId" IS NOT NULL));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_calorimetric_data_CalorimetricDataId" FOREIGN KEY ("CalorimetricDataId") REFERENCES database.calorimetric_data ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_geometric_data_GeometricDataId" FOREIGN KEY ("GeometricDataId") REFERENCES database.geometric_data ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_hygrothermal_data_HygrothermalDataId" FOREIGN KEY ("HygrothermalDataId") REFERENCES database.hygrothermal_data ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_optical_data_OpticalDataId" FOREIGN KEY ("OpticalDataId") REFERENCES database.optical_data ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_photovoltaic_data_PhotovoltaicDataId" FOREIGN KEY ("PhotovoltaicDataId") REFERENCES database.photovoltaic_data ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_id_cannot_change"() RETURNS trigger as $LC_TRIGGER_data_id_cannot_change$
    BEGIN
      IF COALESCE(OLD."CalorimetricDataId", OLD."GeometricDataId", OLD."HygrothermalDataId", OLD."OpticalDataId", OLD."PhotovoltaicDataId") <> COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
    THEN
        RAISE EXCEPTION 'You cannot change the data ID of a resource.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_id_cannot_change$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_id_cannot_change BEFORE UPDATE
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_id_cannot_change"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_ids_must_match"() RETURNS trigger as $LC_TRIGGER_data_ids_must_match$
    BEGIN
      IF NEW."ParentId" IS NOT NULL
       AND (
           SELECT COUNT("Id")
           FROM database."get_https_resource"
           WHERE "Id" = NEW."ParentId" AND COALESCE("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "OpticalDataId", "PhotovoltaicDataId") = COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
       )
       <> 1
    THEN
        RAISE EXCEPTION 'The new resource must have the same data ID as its parent.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_ids_must_match$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_ids_must_match BEFORE INSERT
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_ids_must_match"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113172901_CheckResourcesForConsistency') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113172901_CheckResourcesForConsistency', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125181102_MirrorWidthAndHeightOfGeometricData') THEN
    ALTER TABLE database.geometric_data ADD "Heights" double precision[] NOT NULL DEFAULT ARRAY[]::double precision[];
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125181102_MirrorWidthAndHeightOfGeometricData') THEN
    ALTER TABLE database.geometric_data ADD "Widths" double precision[] NOT NULL DEFAULT ARRAY[]::double precision[];
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251125181102_MirrorWidthAndHeightOfGeometricData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251125181102_MirrorWidthAndHeightOfGeometricData', '9.0.10');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    DROP FUNCTION "database"."LC_TRIGGER_data_id_cannot_change"() CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    DROP FUNCTION "database"."LC_TRIGGER_data_ids_must_match"() CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource DROP CONSTRAINT "CK_GetHttpsResource_Exactly_One_Data_Set";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TYPE database.data_kind ADD VALUE 'life_cycle_data' AFTER 'hygrothermal_data';
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'database') THEN
            CREATE SCHEMA database;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD "LifeCycleDataId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid,
        "Locale" text NOT NULL,
        "ComponentId" uuid NOT NULL,
        "Name" text,
        "Description" text,
        "Warnings" text[] NOT NULL,
        "CreatorId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "AppliedMethod_MethodId" uuid NOT NULL,
        "Approval_Timestamp" timestamp with time zone,
        "Approval_Signature" text,
        "Approval_KeyFingerprint" text,
        "Approval_Query" text,
        "Approval_Variables" jsonb DEFAULT ('{}'),
        "Approval_Message" text,
        "Approval_ApproverId" uuid,
        "DataAccessRights_AllowedUserAndQuantity" jsonb,
        "DataAccessRights_AllowedInstitutions" uuid[],
        "DataAccessRights_AllowedApplications" text[],
        "PublishingState" database.publishing_state NOT NULL,
        CONSTRAINT "PK_lifeCycle_data" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Approvals" (
        "LifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ApproverId" uuid NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Signature" text NOT NULL,
        "KeyFingerprint" text NOT NULL,
        "Query" text NOT NULL,
        "Variables" jsonb NOT NULL DEFAULT ('{}'),
        "Message" text NOT NULL,
        "Statement_Standard_Year" integer,
        "Statement_Standard_Numeration_Prefix" text,
        "Statement_Standard_Numeration_MainNumber" text,
        "Statement_Standard_Numeration_Suffix" text,
        "Statement_Standard_Standardizers" database.standardizer[],
        "Statement_Standard_Locator" text,
        "Statement_Standard_Title" text,
        "Statement_Standard_Abstract" text,
        "Statement_Standard_Section" text,
        "Statement_Publication_Authors" text[],
        "Statement_Publication_Doi" text,
        "Statement_Publication_ArXiv" text,
        "Statement_Publication_Urn" text,
        "Statement_Publication_WebAddress" text,
        "Statement_Publication_Title" text,
        "Statement_Publication_Abstract" text,
        "Statement_Publication_Section" text,
        "Statement_Publication_Exists" boolean,
        "Statement_Exists" boolean NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Approvals" PRIMARY KEY ("LifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Approvals_lifeCycle_data_LifeCycleDataId" FOREIGN KEY ("LifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Arguments" (
        "AppliedMethodLifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Value" jsonb NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Arguments" PRIMARY KEY ("AppliedMethodLifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Arguments_lifeCycle_data_AppliedMethodLifeCy~" FOREIGN KEY ("AppliedMethodLifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE TABLE database."lifeCycle_data_Sources" (
        "AppliedMethodLifeCycleDataId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Value_DataId" uuid NOT NULL,
        "Value_DataTimestamp" timestamp with time zone NOT NULL,
        "Value_DataKind" database.data_kind NOT NULL,
        "Value_DatabaseId" uuid NOT NULL,
        CONSTRAINT "PK_lifeCycle_data_Sources" PRIMARY KEY ("AppliedMethodLifeCycleDataId", "Id"),
        CONSTRAINT "FK_lifeCycle_data_Sources_lifeCycle_data_AppliedMethodLifeCycl~" FOREIGN KEY ("AppliedMethodLifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE UNIQUE INDEX "IX_get_https_resource_LifeCycleDataId" ON database.get_https_resource ("LifeCycleDataId") WHERE "LifeCycleDataId" IS NOT NULL AND "ParentId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "CK_GetHttpsResource_Exactly_One_Data_Set" CHECK (NUM_NONNULLS("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "LifeCycleDataId", "OpticalDataId", "PhotovoltaicDataId") = 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    ALTER TABLE database.get_https_resource ADD CONSTRAINT "FK_get_https_resource_lifeCycle_data_LifeCycleDataId" FOREIGN KEY ("LifeCycleDataId") REFERENCES database."lifeCycle_data" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_id_cannot_change"() RETURNS trigger as $LC_TRIGGER_data_id_cannot_change$
    BEGIN
      IF COALESCE(OLD."CalorimetricDataId", OLD."GeometricDataId", OLD."HygrothermalDataId", OLD."LifeCycleDataId", OLD."OpticalDataId", OLD."PhotovoltaicDataId") <> COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."LifeCycleDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
    THEN
        RAISE EXCEPTION 'You cannot change the data ID of a resource.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_id_cannot_change$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_id_cannot_change BEFORE UPDATE
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_id_cannot_change"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    CREATE FUNCTION "database"."LC_TRIGGER_data_ids_must_match"() RETURNS trigger as $LC_TRIGGER_data_ids_must_match$
    BEGIN
      IF NEW."ParentId" IS NOT NULL
       AND (
           SELECT COUNT("Id")
           FROM database."get_https_resource"
           WHERE "Id" = NEW."ParentId" AND COALESCE("CalorimetricDataId", "GeometricDataId", "HygrothermalDataId", "LifeCycleDataId", "OpticalDataId", "PhotovoltaicDataId") = COALESCE(NEW."CalorimetricDataId", NEW."GeometricDataId", NEW."HygrothermalDataId", NEW."LifeCycleDataId", NEW."OpticalDataId", NEW."PhotovoltaicDataId")
       )
       <> 1
    THEN
        RAISE EXCEPTION 'The new resource must have the same data ID as its parent.';
    END IF;
    RETURN NEW;
    END;
    $LC_TRIGGER_data_ids_must_match$ LANGUAGE plpgsql;
    CREATE TRIGGER LC_TRIGGER_data_ids_must_match BEFORE INSERT
    ON "database"."get_https_resource"
    FOR EACH ROW EXECUTE PROCEDURE "database"."LC_TRIGGER_data_ids_must_match"();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260316165622_AddLifeCycleData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260316165622_AddLifeCycleData', '10.0.2');
    END IF;
END $EF$;
COMMIT;

