using System.Diagnostics.CodeAnalysis;

namespace Database.GraphQl.DataApprovals;

[SuppressMessage("Naming", "CA1707")]
public enum AddDataApprovalErrorCode
{
    UNKNOWN,
    UNAUTHENTICATED,
    UNAUTHORIZED,
    UNKNOWN_DATA,
    CREATING_RESPONSE_APPROVAL_FAILED,
    AMBIGUOUS_STATEMENT,
    MISSING_STATEMENT,
    INVALID_KEY_FINGERPRINT,
    FAILED_RECEIVING_KEY,
    BAD_SIGNATURE,
    FAILED_VERIFYING_SIGNATURE,
    FAILED_VERIFYING_RESPONSE,
    ILLEGAL_MESSAGE,
    WRONG_RESPONSE,
    WRONG_STATEMENT
}